base_model = "deepseek/deepseek-v4-flash"
base_model_omit = ["temperature", "interleaved"]
endpoints = ["openai", "anthropic", "responses"]
doc = "https://ppio.com/llm/deepseek-deepseek-v4-flash"

[limit]
context = 1_048_576
output = 393_216

[cost_cn]
input = 3
output = 9
cache_read = 1
