base_model = "shanghai-ai-lab/intern-s1-pro"
base_model_omit = ["structured_output"]
endpoints = ["openai"]
doc = "https://internlm.openxlab.org.cn/doc/docs/Chat/"

[[reasoning_options]]
type = "toggle"
field = "thinking_mode"
endpoints = ["openai"]
