base_model = "moonshot/kimi-k2.7-code"
base_model_omit = ["structured_output"]
doc = "https://ai.gitee.com/serverless-api?service=14452"

[limit]
context = 256_000

[modalities]
input = ["text", "image"]
output = ["text"]

[cost_cn]
input = 6.5
output = 27
