base_model = "moonshot/kimi-k3"
base_model_omit = ["structured_output", "limit.output"]
doc = "https://ai.gitee.com/serverless-api?service=18314"
temperature = true

[limit]
context = 1_000_000

[modalities]
input = ["text", "image"]
output = ["text"]

[cost_cn]
input = 20
output = 100
