base_model = "minimax/minimax-m3"
base_model_omit = ["structured_output"]
doc = "https://ai.gitee.com/serverless-api?service=12943"

[modalities]
input = ["text", "image"]
output = ["text"]

[cost_cn]
input = 4.2
output = 16.8
