base_model = "alibaba/qwen3.8-max"
base_model_omit = ["reasoning", "structured_output", "limit.input", "limit.output"]
doc = "https://ai.gitee.com/serverless-api?service=19722"
temperature = false

[limit]
context = 1_000_000

[cost_cn]
input = 12
output = 36
