base_model = "stepfun/step-3.7-flash"
base_model_omit = ["reasoning", "structured_output"]
doc = "https://ai.gitee.com/serverless-api?service=17618"

[modalities]
input = ["text", "image"]
output = ["text"]

[cost_cn]
input = 1.35
output = 8.1
