name = "百度智能云千帆"
env = ["QIANFAN_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://qianfan.baidubce.com/v2"
doc = "https://cloud.baidu.com/doc/qianfan/s/rmh4stp0j"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://qianfan.baidubce.com/v2"
default = true

[[endpoints]]
id = "responses"
protocol = "openai-responses"
api = "https://qianfan.baidubce.com/v2"

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://qianfan.baidubce.com/anthropic"
