base_model = "alibaba/qwen3.6-plus"
endpoints = ["openai", "anthropic"]
doc = "https://help.aliyun.com/zh/model-studio/coding-plan-faq"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"
max = 81_920
