name = "无问芯穹 GenStudio"
env = ["GENSTUDIO_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://cloud.infini-ai.com/maas/v1"
doc = "https://docs.infini-ai.com/gen-studio/models/"

[links]
models = "https://cloud.infini-ai.com/genstudio/usage/limit"
pricing = "https://docs.infini-ai.com/gen-studio/api/usage-and-billing/billing.html"
api_key = "https://docs.infini-ai.com/gen-studio/api/get-started/"
console = "https://cloud.infini-ai.com/iam/secret/key"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://cloud.infini-ai.com/maas/v1"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://cloud.infini-ai.com/maas"
