base_model = "alibaba/qwen3.8-flash"
base_model_omit = ["temperature", "interleaved", "limit.input"]
endpoints = ["openai", "anthropic", "responses"]
doc = "https://ppio.com/llm/qwen-qwen3.8-flash"
reasoning = true
tool_call = true
structured_output = true

[limit]
context = 1_000_000
output = 131_072

[modalities]
input = ["text", "image", "video"]
output = ["text"]

[cost_cn]
input = 0.8
output = 2.7
cache_read = 0.1
