base_model = "minimax/minimax-m2.5"
base_model_omit = ["reasoning", "temperature"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.siliconflow.cn/models?target=MiniMaxAI%2FMiniMax-M2.5"
structured_output = true

[limit]
context = 196_608

[cost_cn]
input = 2.1
output = 8.4
cache_read = 0.21
