name = "华为云 MaaS"
env = ["HUAWEI_CLOUD_MAAS_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://api.modelarts-maas.com/openai/v1"
doc = "https://support.huaweicloud.com/model-call-maas/usermanual_maas_0008.html"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://api.modelarts-maas.com/openai/v1"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://api.modelarts-maas.com/anthropic"
