base_model = "deepseek/deepseek-v4.1-flash"
endpoints = ["openai", "anthropic"]
base_model_omit = ["temperature", "structured_output"]
doc = "https://www.volcengine.com/docs/82379/1925114"

[[reasoning_options]]
type = "toggle"

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text", "image"]
output = ["text"]
