base_model = "moonshot/kimi-k3"
endpoints = ["openai", "anthropic"]
base_model_omit = ["reasoning", "temperature", "tool_call", "structured_output", "reasoning_options", "interleaved", "limit.input"]
doc = "https://www.volcengine.com/docs/82379/1925114"

[limit]
context = 1_024_000
output = 131_072

[modalities]
input = ["text", "image"]
output = ["text"]
