base_model = "zhipu/glm-5"
base_model_omit = ["reasoning", "temperature", "tool_call", "structured_output", "limit.output"]
endpoints = ["openai"]
doc = "https://www.ctyun.cn/document/11061839/00000000"
