base_model = "deepseek/deepseek-v4-pro-0813"
base_model_omit = ["temperature"]
name = "DeepSeek V4 Pro 0813（deepseek/deepseek-v4-pro）"
endpoints = ["openai", "anthropic"]
doc = "https://cloud.tencent.com/document/product/1823/130060"

[limit]
output = 393_216
