base_model = "stepfun/step-3.5-flash"
base_model_omit = ["temperature", "reasoning", "interleaved"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.siliconflow.cn/models?target=stepfun-ai%2FStep-3.5-Flash"
structured_output = false

[limit]
context = 262_144

[cost_cn]
input = 0.7
output = 2.1
