base_model = "zhipu/glm-5.3"
base_model_omit = ["temperature"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.tencent.com/document/product/1823/133811"

[cost_points]
per_tokens = 1_000_000
input = 160
output = 560
cache_read = 40
