name = "书生·浦语开放平台"
env = ["INTERNLM_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://intern.openxlab.org.cn/api/v1"
doc = "https://internlm.openxlab.org.cn/doc/docs/%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8/"

[links]
models = "https://internlm.openxlab.org.cn/doc/docs/%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8/"
api_key = "https://internlm.openxlab.org.cn/doc/docs/%E7%94%A8%E6%88%B7%E9%89%B4%E6%9D%83/"
console = "https://internlm.openxlab.org.cn/api/tokens"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://intern.openxlab.org.cn/api/v1"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://intern.openxlab.org.cn"
