name = "火山引擎方舟 Coding Plan"
env = ["ARK_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://ark.cn-beijing.volces.com/api/coding/v3"
doc = "https://www.volcengine.com/docs/82379/1925114"

[links]
models = "https://www.volcengine.com/docs/82379/1925114"
pricing = "https://www.volcengine.com/activity/codingplan"
api_key = "https://www.volcengine.com/docs/82379/1928261"
console = "https://ark.volcengine.com/region:cn-beijing/apikey"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://ark.cn-beijing.volces.com/api/coding/v3"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://ark.cn-beijing.volces.com/api/coding"

[[endpoints]]
id = "responses"
protocol = "openai-responses"
api = "https://ark.cn-beijing.volces.com/api/coding/v3"
