name = "Kimi For Coding"
env = ["KIMI_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://api.kimi.com/coding/v1"
doc = "https://www.kimi.com/code/docs/"

[links]
models = "https://www.kimi.com/code/docs/"
pricing = "https://www.kimi.com/membership/pricing?from=kfc_docs_overview"
api_key = "https://www.kimi.com/code/docs/"
console = "https://www.kimi.com/code/console"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://api.kimi.com/coding/v1"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://api.kimi.com/coding"
