base_model = "deepseek/deepseek-v4-flash"
base_model_omit = ["temperature"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.siliconflow.cn/models?target=deepseek-ai%2FDeepSeek-V4-Flash"

[limit]
context = 1_048_576

[[reasoning_options]]
type = "effort"
field = "reasoning_effort"
endpoints = ["openai"]
values = ["high", "max"]
default = "high"

[interleaved]
field = "reasoning_content"

[cost_cn]
input = 1.5
output = 4.5
cache_read = 0.15

[[cost_cn.tiers]]
input = 1.5
output = 4.5
cache_read = 0.15

[cost_cn.tiers.tier]
type = "conditional"
label = "闲时"

[cost_cn.tiers.tier.time]
timezone = "Asia/Shanghai"

[[cost_cn.tiers.tier.time.windows]]
start = "02:00"
end = "08:00"

[[cost_cn.tiers]]
input = 3
output = 9
cache_read = 0.3

[cost_cn.tiers.tier]
type = "conditional"
label = "其他时间"

[cost_cn.tiers.tier.time]
timezone = "Asia/Shanghai"

[[cost_cn.tiers.tier.time.windows]]
start = "00:00"
end = "02:00"

[[cost_cn.tiers.tier.time.windows]]
start = "08:00"
end = "24:00"
