name = "InternVL 3.5 241B A28B"
description = "上海人工智能实验室推出的开放权重多模态模型，强化图文理解和长时序图片理解。"
family = "internvl"
release_date = "2025-08-28"
last_updated = "2025-08-28"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = false
open_weights = true

[limit]
context = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]

[[links]]
label = "Intern 模型列表"
url = "https://internlm.openxlab.org.cn/doc/docs/%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8/"
type = "docs"
