base_model = "bytedance/doubao-seed-2.1-lite"
base_model_omit = ["limit.input", "reasoning", "temperature", "tool_call", "structured_output"]
doc = "https://www.volcengine.com/docs/82379/2366394?lang=zh"

[limit]
context = 1_024_000
output = 262_144

[modalities]
input = ["text", "image"]
output = ["text"]
