base_model = "zhipu/glm-5.3"
base_model_omit = ["temperature", "tool_call", "structured_output"]
doc = "https://www.volcengine.com/docs/82379/2366394?lang=zh"

[limit]
context = 1_024_000
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
