base_model = "zhipu/glm-5.3-flash"
base_model_omit = ["temperature", "interleaved", "limit.input"]
endpoints = ["openai", "anthropic", "responses"]
doc = "https://ppio.com/llm/zai-org-glm-5.3-flash"
reasoning = true
tool_call = true
structured_output = true

[limit]
context = 1_048_576
output = 131_072

[modalities]
input = ["text", "image", "video"]
output = ["text"]

[cost_cn]
input = 0.8
output = 2.8
cache_read = 0.23
