base_model = "deepseek/deepseek-v4-flash-0731"
base_model_omit = ["reasoning", "temperature", "tool_call", "structured_output", "limit.output"]
endpoints = ["openai", "anthropic"]
doc = "https://www.ctyun.cn/document/11061839/11095143"
