base_model = "baidu/ernie-4.5-turbo"
base_model_omit = ["tool_call", "structured_output", "reasoning_options", "interleaved"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.baidu.com/doc/qianfan/s/imlg0beiu"
temperature = true

[limit]
context = 138_240
input = 125_952
output = 12_288
