base_model = "minimax/minimax-m2.5"
endpoints = ["openai", "anthropic", "responses"]
name = "MiniMax M2.5 Highspeed"
doc = "https://platform.minimaxi.com/docs/guides/text-generation"

[interleaved]
field = "reasoning_details"

[provider.body]
reasoning_split = true

[cost_cn]
input = 4.2
output = 16.8
cache_read = 0.21
cache_write = 2.625
