base_model = "minimax/minimax-m2.1"
endpoints = ["openai", "anthropic"]
name = "MiniMax M2.1 Highspeed"
doc = "https://platform.minimaxi.com/docs/guides/text-generation"

[[reasoning_options]]
type = "effort"
values = ["default"]

[interleaved]
field = "reasoning_details"

[provider.body]
reasoning_split = true

[cost_cn]
input = 4.2
output = 16.8
cache_read = 0.21
cache_write = 2.625
