name = "Alibaba (China)"
env = ["DASHSCOPE_API_KEY"]
npm = "@ai-sdk/openai-compatible"
api = "https://dashscope.aliyuncs.com/compatible-mode/v1"
doc = "https://www.alibabacloud.com/help/en/model-studio/models"
