name = "阿里云百炼"
env = ["DASHSCOPE_API_KEY"]
npm = "@ai-sdk/openai-compatible"
protocol = "openai-compatible"
api = "https://dashscope.aliyuncs.com/compatible-mode/v1"
doc = "https://help.aliyun.com/zh/model-studio/getting-started/models"

[links]
models = "https://help.aliyun.com/zh/model-studio/getting-started/models"
pricing = "https://help.aliyun.com/zh/model-studio/model-pricing"
api_key = "https://help.aliyun.com/zh/model-studio/get-api-key"
console = "https://bailian.console.aliyun.com/cn-beijing?tab=model#/api-key"

[[endpoints]]
id = "openai"
protocol = "openai-compatible"
api = "https://dashscope.aliyuncs.com/compatible-mode/v1"
default = true

[[endpoints]]
id = "anthropic"
protocol = "anthropic-compatible"
api = "https://dashscope.aliyuncs.com/apps/anthropic"

[[endpoints]]
id = "responses"
protocol = "openai-responses"
api = "https://dashscope.aliyuncs.com/compatible-mode/v1"
