base_model = "zhipu/glm-5.3-flash"
base_model_omit = ["temperature", "tool_call", "structured_output"]
endpoints = ["openai"]
doc = "https://cloud.baidu.com/doc/qianfan/s/rmh4stp0j"

reasoning = true

[limit]
context = 1_000_000
input = 1_000_000
output = 131_072

[cost_cn]
input = 0.8
output = 2.8
cache_read = 0.23
