base_model = "alibaba/qwen3.5-122b-a10b"
base_model_omit = ["temperature", "tool_call", "structured_output"]
endpoints = ["openai", "anthropic"]
doc = "https://cloud.baidu.com/doc/qianfan/s/rmh4stp0j"

[limit]
context = 256_000
input = 252_000
output = 65_536

[cost_cn]
input = 0.8
output = 6.4

[[cost_cn.tiers]]
input = 0.8
output = 6.4
[cost_cn.tiers.tier]
type = "conditional"
[cost_cn.tiers.tier.input]
lte = 128_000

[[cost_cn.tiers]]
input = 2
output = 16
[cost_cn.tiers.tier]
type = "conditional"
[cost_cn.tiers.tier.input]
gt = 128_000
lte = 256_000
